package com.wedding.service.api;

import com.wedding.service.security.Principal;
import com.wedding.service.service.DataService;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import java.security.SecureRandom;
import java.time.*;
import java.util.*;
import org.springframework.http.*;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/internal")
public class InternalController {
 private final DataService db; private final SecureRandom random=new SecureRandom(); InternalController(DataService db){this.db=db;}
 public record PartyInput(@NotBlank String displayName,String contactEmail,String contactPhone,@NotBlank String verificationQuestion,@NotBlank String verificationAnswer) {}
 public record GuestInput(@NotBlank String firstName,@NotBlank String lastName,String relationshipGroup,String email,String phone,String dietaryRequirements,String accessibilityNeeds,String travelOrigin,String flightNumber,String plannerNotes,boolean additionalGuest) {}
 public record EntityInput(Map<String,Object> values) {} public record ManualRsvp(@NotBlank String status,String note) {} public record Delivery(@NotBlank String kind,String note) {}
 @GetMapping("/parties") List<Map<String,Object>> parties(@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="50") int size,@RequestParam(required=false) String q){ var ps=new org.springframework.jdbc.core.namedparam.MapSqlParameterSource().addValue("s",Math.min(size,100)).addValue("o",Math.max(page,0)*Math.min(size,100)); String sql="SELECT id,display_name,contact_email,contact_phone,archived,created_at FROM party WHERE archived=false"; if(q!=null&&!q.isBlank()){sql+=" AND display_name ILIKE '%'||:q||'%'";ps.addValue("q",q);} return db.named.queryForList(sql+" ORDER BY display_name LIMIT :s OFFSET :o",ps); }
 @PostMapping("/parties") ResponseEntity<Map<String,Object>> party(@AuthenticationPrincipal Principal actor,@Valid @RequestBody PartyInput in){ UUID id=db.uuid(); db.named.update("INSERT INTO party(id,display_name,contact_email,contact_phone,verification_question,verification_answer_hash) VALUES(:id,:n,:e,:p,:q,:a)",Map.of("id",id,"n",in.displayName(),"e",in.contactEmail()==null?"":in.contactEmail(),"p",in.contactPhone()==null?"":in.contactPhone(),"q",in.verificationQuestion(),"a",db.passwords.encode(in.verificationAnswer().trim().toLowerCase()))); db.audit(actor.id(),"CREATE","PARTY",id,null,in); return ResponseEntity.status(HttpStatus.CREATED).body(db.one("SELECT id,display_name,contact_email,contact_phone FROM party WHERE id=:id",Map.of("id",id))); }
 @PostMapping("/parties/{partyId}/guests") ResponseEntity<Map<String,Object>> guest(@AuthenticationPrincipal Principal actor,@PathVariable UUID partyId,@Valid @RequestBody GuestInput in){db.one("SELECT id FROM party WHERE id=:id",Map.of("id",partyId)); UUID id=db.uuid(); var p=new org.springframework.jdbc.core.namedparam.MapSqlParameterSource().addValue("id",id).addValue("partyId",partyId).addValue("firstName",in.firstName()).addValue("lastName",in.lastName()).addValue("relationshipGroup",in.relationshipGroup()).addValue("email",in.email()).addValue("phone",in.phone()).addValue("dietaryRequirements",in.dietaryRequirements()).addValue("accessibilityNeeds",in.accessibilityNeeds()).addValue("travelOrigin",in.travelOrigin()).addValue("flightNumber",in.flightNumber()).addValue("plannerNotes",in.plannerNotes()).addValue("additionalGuest",in.additionalGuest()); db.named.update("INSERT INTO guest(id,party_id,first_name,last_name,relationship_group,email,phone,dietary_requirements,accessibility_needs,travel_origin,flight_number,planner_notes,is_additional_guest) VALUES(:id,:partyId,:firstName,:lastName,:relationshipGroup,:email,:phone,:dietaryRequirements,:accessibilityNeeds,:travelOrigin,:flightNumber,:plannerNotes,:additionalGuest)",p); db.audit(actor.id(),"CREATE","GUEST",id,null,in); return ResponseEntity.status(201).body(db.one("SELECT * FROM guest WHERE id=:id",Map.of("id",id))); }
 @PostMapping("/parties/{id}/invitations") Map<String,Object> invitation(@AuthenticationPrincipal Principal actor,@PathVariable UUID id,@RequestParam(required=false) Integer expiresDays){ db.one("SELECT id FROM party WHERE id=:id",Map.of("id",id)); String token=UUID.randomUUID()+"-"+Long.toUnsignedString(random.nextLong(),36); UUID invite=db.uuid(); OffsetDateTime expiry=expiresDays==null?null:OffsetDateTime.now().plusDays(expiresDays); db.named.update("INSERT INTO invitation(id,party_id,token,token_hash,token_expires_at) VALUES(:i,:p,:tok,:t,:e) ON CONFLICT(party_id) DO UPDATE SET token=excluded.token,token_hash=excluded.token_hash,token_expires_at=excluded.token_expires_at,status='DRAFT'",new org.springframework.jdbc.core.namedparam.MapSqlParameterSource().addValue("i",invite).addValue("p",id).addValue("tok",token).addValue("t",db.hashToken(token)).addValue("e",expiry)); db.audit(actor.id(),"ISSUE_QR","INVITATION",invite,null,Map.of("partyId",id)); return Map.of("qrToken",token,"expiresAt",expiry==null?"":expiry.toString()); }
 @PostMapping("/invitations/{id}/record-delivery") Map<String,Object> delivery(@AuthenticationPrincipal Principal p,@PathVariable UUID id,@Valid @RequestBody Delivery in){ UUID d=db.uuid(); String k=in.kind().toUpperCase(); if(!List.of("DELIVERY","REMINDER").contains(k)) throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_DELIVERY","kind must be DELIVERY or REMINDER"); db.named.update("INSERT INTO invitation_delivery(id,invitation_id,kind,note,recorded_by) VALUES(:i,:v,:k,:n,:p)",Map.of("i",d,"v",id,"k",k,"n",in.note()==null?"":in.note(),"p",p.id())); if("DELIVERY".equals(k)) db.named.update("UPDATE invitation SET status='SENT',sent_at=COALESCE(sent_at,now()) WHERE id=:id",Map.of("id",id)); return Map.of("id",d,"kind",k); }
 @PostMapping("/events") ResponseEntity<Map<String,Object>> event(@AuthenticationPrincipal Principal actor,@RequestBody Map<String,Object> in){ UUID id=db.uuid(); db.named.update("INSERT INTO event(id,venue_id,name,description,starts_at,ends_at,dress_code,capacity,rsvp_deadline,public_visible) VALUES(:id,cast(:venueId as uuid),:name,:description,cast(:startsAt as timestamptz),cast(:endsAt as timestamptz),:dressCode,cast(:capacity as integer),cast(:deadline as timestamptz),:publicVisible)",params(in).addValue("id",id).addValue("venueId",in.get("venueId")).addValue("startsAt",in.get("startsAt")).addValue("endsAt",in.get("endsAt")).addValue("deadline",in.get("rsvpDeadline")).addValue("publicVisible",in.get("publicVisible")==null?Boolean.TRUE:in.get("publicVisible"))); db.audit(actor.id(),"CREATE","EVENT",id,null,in); return ResponseEntity.status(201).body(db.one("SELECT * FROM event WHERE id=:id",Map.of("id",id))); }
 @PostMapping("/events/{eventId}/eligible-parties/{partyId}") Map<String,Object> eligible(@PathVariable UUID eventId,@PathVariable UUID partyId){ db.named.update("INSERT INTO event_eligibility(event_id,party_id) VALUES(:e,:p) ON CONFLICT DO NOTHING",Map.of("e",eventId,"p",partyId)); List<Map<String,Object>> gs=db.many("SELECT id FROM guest WHERE party_id=:p AND active",Map.of("p",partyId)); for(var g:gs) db.named.update("INSERT INTO rsvp(guest_id,event_id) VALUES(:g,:e) ON CONFLICT DO NOTHING",Map.of("g",g.get("id"),"e",eventId)); return Map.of("eventId",eventId,"partyId",partyId,"rsvpsCreated",gs.size()); }
 @PutMapping("/rsvps/{id}") Map<String,Object> manualRsvp(@AuthenticationPrincipal Principal p,@PathVariable UUID id,@Valid @RequestBody ManualRsvp in){ String s=in.status().toUpperCase(); if(!List.of("ATTENDING","DECLINED","PENDING","WAITLISTED").contains(s)) throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_RSVP","Invalid RSVP status"); var before=db.one("SELECT * FROM rsvp WHERE id=:id",Map.of("id",id)); db.named.update("UPDATE rsvp SET status=:s,note=:n,source='PLANNER',updated_at=now() WHERE id=:id",Map.of("s",s,"n",in.note()==null?"":in.note(),"id",id)); var after=db.one("SELECT * FROM rsvp WHERE id=:id",Map.of("id",id)); db.audit(p.id(),"UPDATE","RSVP",id,before,after); return after; }
 @PostMapping("/venues") ResponseEntity<Map<String,Object>> venue(@AuthenticationPrincipal Principal p,@RequestBody Map<String,Object> in){return createSimple(p,"venue",in,List.of("name","address","contact_information","pricing","capacity","food_score","view_score","notes"));}
 @PostMapping("/accommodations/properties") ResponseEntity<Map<String,Object>> property(@AuthenticationPrincipal Principal p,@RequestBody Map<String,Object> in){return createSimple(p,"accommodation_property",in,List.of("name","address","contact_information","notes"));}
 @PostMapping("/accommodations/rooms") ResponseEntity<Map<String,Object>> room(@AuthenticationPrincipal Principal p,@RequestBody Map<String,Object> in){return createSimple(p,"accommodation_room",in,List.of("property_id","room_number","room_type","capacity"));}
 @PostMapping("/accommodations/assignments") ResponseEntity<Map<String,Object>> assignment(@AuthenticationPrincipal Principal p,@RequestBody Map<String,Object> in){ UUID id=db.uuid(); UUID room=UUID.fromString(in.get("room_id").toString()); int cap=db.jdbc.queryForObject("SELECT capacity FROM accommodation_room WHERE id=?",Integer.class,room); int occupants=in.get("guest_id")!=null?1:db.jdbc.queryForObject("SELECT count(*) FROM guest WHERE party_id=? AND active",Integer.class,UUID.fromString(in.get("party_id").toString())); boolean override=Boolean.TRUE.equals(in.get("override_capacity")); int booked=db.jdbc.queryForObject("SELECT coalesce(sum(CASE WHEN guest_id IS NOT NULL THEN 1 ELSE (SELECT count(*) FROM guest g WHERE g.party_id=a.party_id AND g.active) END),0) FROM accommodation_assignment a WHERE room_id=? AND status <> 'CANCELLED' AND check_in < ?::date AND check_out > ?::date",Integer.class,room,in.get("check_out").toString(),in.get("check_in").toString()); if(!override && booked+occupants>cap) throw new ApiException(HttpStatus.CONFLICT,"ROOM_CAPACITY","Assignment would exceed room capacity"); var ps=params(in).addValue("id",id); db.named.update("INSERT INTO accommodation_assignment(id,room_id,party_id,guest_id,check_in,check_out,status,coverage_notes,override_capacity) VALUES(:id,cast(:room_id as uuid),cast(:party_id as uuid),cast(:guest_id as uuid),cast(:check_in as date),cast(:check_out as date),:status,:coverage_notes,:override_capacity)",ps); db.audit(p.id(),override?"OVERRIDE_CAPACITY":"CREATE","ACCOMMODATION_ASSIGNMENT",id,null,in); return ResponseEntity.status(201).body(db.one("SELECT * FROM accommodation_assignment WHERE id=:id",Map.of("id",id))); }
 @PostMapping("/budget/categories") ResponseEntity<Map<String,Object>> budgetCategory(@AuthenticationPrincipal Principal p,@RequestBody Map<String,Object> in){return createSimple(p,"budget_category",in,List.of("name"));}
 @PostMapping("/budget/contributors") ResponseEntity<Map<String,Object>> contributor(@AuthenticationPrincipal Principal p,@RequestBody Map<String,Object> in){return createSimple(p,"budget_contributor",in,List.of("name"));}
 @PostMapping("/budget/line-items") ResponseEntity<Map<String,Object>> lineItem(@AuthenticationPrincipal Principal p,@RequestBody Map<String,Object> in){return createSimple(p,"budget_line_item",in,List.of("category_id","description","currency","planned_amount","actual_amount","payment_status","due_date","notes"));}
 @PostMapping("/site/things-to-do-items") ResponseEntity<Map<String,Object>> thingToDoItem(@AuthenticationPrincipal Principal p,@RequestBody Map<String,Object> in){return createSimple(p,"thing_to_do_item",in,List.of("category","title","description","image_id","sort_order"));}
 private ResponseEntity<Map<String,Object>> createSimple(Principal p,String table,Map<String,Object> input,List<String> fields){ if(fields.stream().anyMatch(f->!input.containsKey(f) && f.equals("name"))) throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","name is required"); UUID id=db.uuid(); List<String> cols=new ArrayList<>();List<String> vals=new ArrayList<>(); var ps=params(input).addValue("id",id);cols.add("id");vals.add(":id");for(String f:fields)if(input.containsKey(f)){cols.add(f);vals.add(":"+f);} db.named.update("INSERT INTO "+table+"("+String.join(",",cols)+") VALUES("+String.join(",",vals)+")",ps);db.audit(p.id(),"CREATE",table.toUpperCase(),id,null,input);return ResponseEntity.status(201).body(db.one("SELECT * FROM "+table+" WHERE id=:id",Map.of("id",id))); }
 private org.springframework.jdbc.core.namedparam.MapSqlParameterSource params(Map<String,Object> values){var p=new org.springframework.jdbc.core.namedparam.MapSqlParameterSource();values.forEach((k,v)->p.addValue(k,db.coerceUuidLike(k,v)));return p;}
}
