ALTER TABLE venue ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE event ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE accommodation_property ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE accommodation_room ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE budget_category ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE budget_contributor ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE budget_line_item ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX guest_email_unique_when_present ON guest (lower(email)) WHERE email IS NOT NULL AND active;
